//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphanem
{
    using System;
    using System.Collections.Generic;
    
    public partial class KitapTur
    {
        public int kitapTurID { get; set; }
        public Nullable<int> kitapID { get; set; }
        public Nullable<int> turID { get; set; }
    
        public virtual Kitap Kitap { get; set; }
        public virtual Tur Tur { get; set; }
    }
}
