//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphanem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitabım
    {
        public int kitabımID { get; set; }
        public int kitapID { get; set; }
        public int kullaniciID { get; set; }
        public string durum { get; set; }
    
        public virtual Kitap Kitap { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
