//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphanem
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonBook
    {
        public int BookID { get; set; }
        public int PersonID { get; set; }
        public string Status { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Person Person { get; set; }
    }
}
