//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphanem
{
    using System;
    using System.Collections.Generic;
    
    public partial class YazarKitap
    {
        public int yazarKitapID { get; set; }
        public Nullable<int> kitapID { get; set; }
        public Nullable<int> yazarID { get; set; }
    
        public virtual Kitap Kitap { get; set; }
        public virtual Yazar Yazar { get; set; }
    }
}
